export enum IconName {
  NavBack = "NavBack",
  Save = "Save",
  Reload = "Reload",
  ChevronLeft = "ChevronLeft",
  ChevronRight = "ChevronRight",
  Close = "Close",
  Search = "Search",
  Edit = "Edit",
  Add = "Add",
  Images = "Images",
  DragAndDrop = "DragAndDrop",
  Delete = "Delete",
  Loader = "Loader",
  Check = "Check",
  LocalError = "LocalError",
  Calendar = "Calendar",
  Random = "Random",
  Dot = "Dot",
  User = "User",
  Login = "Login",
  Logout = "Logout",
  Show = "Show",
  Hide = "Hide",
  Copy = "Copy"
}
